### PR TITLE
TESB416-201

### PR DESCRIPTION
**Pull request by flitzpiepe96**
Web app is independent of repositories. All database calls are made via REST

### CODE REVIEW

**Comment by rgcjonas** [comment]
Wait a moment didn't this fail in Jenkins?

**Comment by flitzpiepe96** [comment]
Yes it did fail. I created this pull request before jenkins completed, because I did not expect this to fail at all. Of course I won't merge before I fixed the issue, but I'm still failing to figure out why the most recent commit broke the tests.

**Comment by flitzpiepe96** [comment]
Jenkins build is stable now. This branch could be merged if the changes are approved

**Comment by rgcjonas** [comment]
Looks great. Merge is on the way!

**Pull request merged**
